fix(parser): Tighten up regex for dates parsing
This PR fixes `panic`:  panicked at 'No such local time' when we using
parsed data to create DateTime.

* Tiighten up the regex for date parsing and make sure we properly
  extract month and day numbers.
* Use *_opt variants of the function which return Options instead of
  just unwraping the value.

This actually will ignore the input log line if either regex fails to
extract the numbers or creation of the date is not posible.